---
development:
  dialect: postgres
  database: symptoms_tracker_development
  user: ale
  password: pass
  host: 127.0.0.1
  pool: 5

test:
  url: {{envOr "TEST_DATABASE_URL" "postgres://ale:pass@127.0.0.1:5432/symptoms_tracker_test?sslmode=disable"}}

production:
  url: {{envOr "DATABASE_URL" "postgres://ale:pass@127.0.0.1:5432/symptoms_tracker_production?sslmode=disable"}}
